
[testenv]
whitelist_externals = git
setenv =
    PYTHONPATH = {toxinidir}
passenv = *
deps =
    pytest
    coverage
commands =
    coverage run --omit tests --omit venv --omit .tox -m pytest  --ignore=s2_rut_python/snap-rut --basetemp='{envtmpdir}' {posargs}
    coverage report

[coverage:run]
source = s2_rut_python
